# Lecturer's department model

from models import Lecturers,Student,Courses
from flask import render_template,flash,redirect,request,redirect,url_for,session
from flask import Blueprint
from extentions import db
from models import Department,Student,Lecturers,Courses
import uuid

department = Blueprint("lecturers_department", __name__)

@department.route("/lec_department", methods=["GET","POST"])
def lec_department():
    lec_id = session.get("lec_id")
    lecturer = Lecturers.query.get(lec_id)

    if request.method == "POST":
        dept_name = request.form.get("department")
        selected_courses = request.form.getlist("courses")
        lecturer.department = dept_name

         # check for department name and
        existing_dept = Department.query.filter_by(dept_name=dept_name).first()
        #compare wether the department name already exists or not if "yes" department id remains thesame
        if existing_dept:
          dept_id=existing_dept.dept_id
        else:
        # if "no" department id is generated by uuid with only 6 characters long"
         dept_id = str(uuid.uuid4())[:6] 
        
        for course_id in selected_courses:
          course = Courses.query.get(course_id)
          if course: 
              department = Department(dept_id=dept_id, dept_name=dept_name, course_id=course_id,lec_id=lecturer.lec_id)
              db.session.add(department)
        db.session.commit()
        flash(f"You have been assigned to {dept_name}. Go to the HoD for course assignment.", "info")
        return redirect(url_for("login.login_L"))

    return render_template("department.html", lecturer=lecturer)


